workflows:
  build-windows-app:
    name: Build Windows EXE
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Enable Windows support
        script: |
          flutter config --enable-windows-desktop
      - name: Build Windows app
        script: |
          flutter build windows
    artifacts:
      - build/windows/runner/Release/*.exe
