name: Build Windows App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

      - name: Install Visual Studio Build Tools with C++ Desktop Workload
        run: |
          choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --quiet --norestart" --no-progress
          refreshenv

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'  # تأكد إن النسخة دي متوافقة مع مشروعك

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Run Flutter Doctor
        run: flutter doctor -v

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows app
        run: flutter build windows

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-app-exe
          path: build/windows/runner/Release/
