name: Build Windows App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'

      - name: Enable Windows platform
        run: flutter config --enable-windows-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows app
        run: flutter build windows

      - name: Show build folder contents
        run: |
          echo "== Directory Content =="
          Get-ChildItem -Recurse build\windows\runner | Out-String | Write-Output

      - name: Upload EXE file only
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: build/windows/runner/Release/*.exe
